name: Deploy Firebase

on:
  push:
    branches:
      - main  # Altere para a branch correta do seu projeto

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Certifique-se de que a versão correta do Node está definida

      - name: Instalar dependências
        run: npm install

      - name: Configurar credenciais do Firebase
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' > $HOME/firebase.json

      - name: Exportar variável de ambiente
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase.json" >> $GITHUB_ENV

      - name: Verificar autenticação Firebase
        run: firebase projects:list

      - name: Fazer deploy no Firebase
        run: firebase deploy --only hosting
