name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Configurar credenciais do Firebase
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      - name: Fazer o build do projeto
        run: npm run build

      - name: Deploy no Firebase Hosting
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"
          firebase deploy --project esp32-309d2
