name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Instalar dependências
        run: npm install

      - name: Verificar se os secrets estão sendo carregados
        run: |
          if [ -z "${{ secrets.VITE_FIREBASE_API_KEY }}" ]; then
            echo "❌ VITE_FIREBASE_API_KEY está vazio!"
            exit 1
          else
            echo "✅ VITE_FIREBASE_API_KEY foi carregado corretamente."
          fi

      - name: Criar arquivo .env
        run: |
          cat <<EOF > .env
          VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_DATABASE_URL=${{ secrets.VITE_FIREBASE_DATABASE_URL }}
          VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}
          EOF

      - name: Verificar conteúdo do .env
        run: cat .env

      - name: Fazer build do projeto
        run: npm run build

      - name: Criar credencial Firebase
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ESP32_309D2 }}" > firebase-service-account.json

      - name: Deploy no Firebase
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
