name: Build and Deploy

on:
  push:
    branches:
      - main  # Certifique-se de que esta é a branch correta

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build-prod

      - name: Arquivar artefato de produção
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Baixar artefato
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy no Firebase
        uses: w9jds/firebase-action@v11
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
