name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Verificar se Vite está instalado
        run: npm list vite

      - name: Fazer o build do projeto
        run: npm run build

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy no Firebase Hosting
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
