name: Deploy Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Limpar caches antigos
        run: |
          rm -rf ~/.npm
          rm -rf node_modules
          rm -rf package-lock.json
          npm cache clean --force

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Deploy para Firebase Hosting
        run: firebase deploy --only hosting --project esp32-309d2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}